config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'splash#index'
  # get 'users/index'
  resources :categories, only: [:index, :show, :new, :create, :destroy] do 
    resources :category_details, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if (user.role = 'admin')
      can :manage, Category, user_id: user.id
      can :manage, CategoryDetail, users_id: user.id
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :users, class_name: 'User', foreign_key: 'user_id'
  has_many :category_details, class_name: 'CategoryDetail'

  validates :name, presence: true, length: { in: 1..50 }
  validates :icon, presence: true
end

app/models/category_detail.rb
class CategoryDetail < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :categories, class_name: 'Category', foreign_key: 'category_id'
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, foreign_key: 'user_id'
  has_many :category_details, foreign_key: 'author_id'
  validates :name, presence: true, length: { in: 1..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @category_details = @category.category_details.order(created_at: :desc)
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.html { render :new, locals: { category: @category } }
    end
  end

  def create
    @category = Category.new(strong_params.merge(user_id: current_user.id))
    respond_to do |format|
      format.html do
        if @category.save!
          flash[:success] = 'category saved successfully'
          redirect_to categories_path
        else
          flash.now[:error] = 'Error: category could not be saved'
          render :new, locals: { category: @category }
        end
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = 'category deleted successfully'
      redirect_to categories_path
    else
      flash.now[:error] = 'Error: category could not be delete'
    end
  end

  private

  def strong_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/category_details_controller.rb
class CategoryDetailsController < ApplicationController
  before_action :authenticate_user!
  def new
    @category = Category.find(params[:category_id])
    @category_detail = CategoryDetail.new
    respond_to do |format|
      format.html { render :new, locals: { category: @category, category_detail: @category_detail } }
    end
  end

  def create
    @category_detail = CategoryDetail.new(strong_params.merge(author_id: current_user.id,
                                                              category_id: params[:category_id]))
    # @category_detail.category = @category
    respond_to do |format|
      format.html do
        if @category_detail.save!
          flash[:success] = 'transition saved successfully'
          redirect_to categories_path
        else
          flash.now[:error] = 'Error: transition could not be saved'
          render :new, locals: { category: @category, category_detail: @category_detail }
        end
      end
    end
  end

  private

  def strong_params
    params.require(:transition).permit(:name, :amount, :categories_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_details_helper.rb
module CategoryDetailsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<section class='category-container'>
<% if @categories.blank? %>
<p>There is no category to show , create one!</p>
<% else %>
<% @categories.each do |category| %>
<div class='card-container'>
<img src='<%= category.icon %>' alt='category icon' class='card-img' />
<div class='card-info'>
<p class='category-name'><%= link_to category.name, {:action => 'show', :id => category.id } %></p>
<p><%= category.created_at.strftime("%d %b %Y") %></p>
</div>
<% if can? :destroy, category %>
  <%= button_to "Delete", category_path(category), method: :delete, class: "category-btn", data: { confirm: 'Are you sure?' } %>
<% end %>
</div>
<% end %>
<% end %>
<%= link_to 'Add new category', new_category_path, class:"btn" %>
</section>

app/views/categories/new.html.erb
<section class='signin-container'>
<h1>Add a new category.</h1>

<%= form_with model: @category, url: categories_path, method: :post, scope: :category, locals: { category: @category } do |form| %>

<div class='form-item'>
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class:"input-form" %>
</div>

<div class='form-item'>
      <%= form.label :icon, class: 'form-label' %>
      <%= form.text_field :icon, class:"input-form" %>
</div>

<%= form.submit "Add category" , class:"form-button" %>
  <% end %>

  <%= link_to 'back', categories_path %>

</section>

app/views/categories/show.html.erb
<section class='signin-container'>
<div class='show'>
<div class='category-info'>
<img src='<%= @category.icon %>' alt='category icon' class='card-img' />
<h1 class='category-name'> <%= @category.name %></h1>
</div>
<% @category_details.each do |detail|%>
<div class='trancition'>
<h1> <%= detail.name %></h1>
<p> $ <%= detail.amount %></p>
</div>
<% end %>
<h4 class='btn'>Total spent:$ <span> <%= @category.category_details.sum(:amount) %></span></h4>
</div>
<%= link_to 'Add new trancition', new_category_category_detail_path(@category), class:"btn" %>

<%= link_to 'back', categories_path %>
</section>

app/views/category_details/new.html.erb
<section class='signin-container'>
<h1>Add transition to the category</h1>
<%= form_with url: category_category_details_path(categories_id: @category.id), scope: :transition do |form| %>
    <div class="form-div" >

  <div class='form-item'>
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class:"input-form" %>
</div>

    <div class='form-item'>
    <%= form.label :amount, class:"form-label" %><br>
    <%= form.number_field :amount , class:"input-form", required: true, placeholder: '1',  min: 1%><br>
  </div>

  <div class='form-item'>
    <%= form.label :category, class: 'form-label' %><br>
    <%= form.select :category_id, @category.users.categories.map {|category| [category.name, category.id]}, { include_blank: true }, class: "input-form" %>
<br>
    </div>
  <div class='form-item'>
    <div>
    <%= form.submit "Add", class:"form-button" %>
    </div>
    </div>
  <%end%>
  <%= link_to 'back', category_path(@category) %>
<section>

app/views/layouts/_navbar.html.erb
<nav class='navbar-container'>
<ul class='nav-menu'>
<% if user_signed_in? %>
    <%= link_to 'Home', root_path , class:"none"%>
    <%= link_to 'Edit', edit_user_registration_path , class:"none" %>
    <%= link_to 'Sign out', destroy_user_session_path, 'data-turbo-method': :delete %>
<% end %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
      <%= render 'layouts/navbar' %>
      <header>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<section class='app-page'>
<h1 class='app-logo'>Siris
</br>
<span class='logo-text'>MANAGE YOUR MONEY</span>
</h1>
<div class='btn-container'>
<%= link_to 'Sign In', new_user_session_path , class: 'login btn' %>
<%= link_to 'Sign Up', new_user_registration_path , class: 'signup btn' %>
</div>
</section>

app/views/users/index.html.erb
<h1><%=  @user.name  %></h1>